// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NPE42V486p0e0evbJ9QmdbeP006rItE',
    appId: '1:825079701626:web:103998ac9dae7077e55bc3',
    messagingSenderId: '825079701626',
    projectId: 'careerconnect-78529',
    authDomain: 'careerconnect-78529.firebaseapp.com',
    storageBucket: 'careerconnect-78529.firebasestorage.app',
    measurementId: 'G-GSFPJTE56W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6URwqPmzeS5wHy8l7Dc9bK8fNn0gvssk',
    appId: '1:825079701626:android:f8dbabee426aa6a6e55bc3',
    messagingSenderId: '825079701626',
    projectId: 'careerconnect-78529',
    storageBucket: 'careerconnect-78529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99WeE-6HlMvVuYHPMXQ_cFDkTwgCZ4qQ',
    appId: '1:825079701626:ios:a21caffdb4ba81f7e55bc3',
    messagingSenderId: '825079701626',
    projectId: 'careerconnect-78529',
    storageBucket: 'careerconnect-78529.firebasestorage.app',
    androidClientId: '825079701626-kudlnc4rlnsrelngihg0r1nmbt7di9oc.apps.googleusercontent.com',
    iosClientId: '825079701626-dgkcaeti6nvah1eko9up37s6ubnt8rgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99WeE-6HlMvVuYHPMXQ_cFDkTwgCZ4qQ',
    appId: '1:825079701626:ios:a21caffdb4ba81f7e55bc3',
    messagingSenderId: '825079701626',
    projectId: 'careerconnect-78529',
    storageBucket: 'careerconnect-78529.firebasestorage.app',
    androidClientId: '825079701626-kudlnc4rlnsrelngihg0r1nmbt7di9oc.apps.googleusercontent.com',
    iosClientId: '825079701626-dgkcaeti6nvah1eko9up37s6ubnt8rgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3NPE42V486p0e0evbJ9QmdbeP006rItE',
    appId: '1:825079701626:web:4e34cb27578c3d87e55bc3',
    messagingSenderId: '825079701626',
    projectId: 'careerconnect-78529',
    authDomain: 'careerconnect-78529.firebaseapp.com',
    storageBucket: 'careerconnect-78529.firebasestorage.app',
    measurementId: 'G-FV8VNFFHF4',
  );
}
